# Generated by Django 3.2.9 on 2021-11-02 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan', models.FileField(upload_to='passports', verbose_name='Passport Scan')),
                ('document', models.CharField(max_length=15, verbose_name='Document ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last name')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Patronymic')),
                ('nationality', models.CharField(max_length=20, verbose_name='Nationality')),
                ('birth', models.DateField(verbose_name='Birthday date')),
                ('personal', models.CharField(max_length=20, unique=True, verbose_name='Personal ID')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], verbose_name='Gender')),
                ('issue_date', models.DateField(verbose_name='Issue date')),
                ('expire_date', models.DateField(verbose_name='Expire date')),
                ('issuing_authority', models.CharField(max_length=35, verbose_name='Issuing authority')),
                ('passports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='passport.customer', verbose_name='Passport')),
            ],
        ),
    ]
