# Generated by Django 3.2.9 on 2021-11-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passport',
            old_name='passports',
            new_name='customer',
        ),
    ]
